[17.0][MIG] rma_scrap
ForgeFlow/stock-rma pull request #514
Opened 2024-05-06 12:00 UTC by AaronHForgeFlow

Supersedes https://github.com/ForgeFlow/stock-rma/pull/504

Respected original code & history

Reasons for supersede:

Merge 17.0 was broken after merging and reverting by mistake some pull requests: https://github.com/ForgeFlow/stock-rma/pull/483 & https://github.com/ForgeFlow/stock-rma/pull/500

History was incorrect showing merge commits within it.
Merge conflicts when trying to manually merge other PRs on top on that one.
Unable to see the changes in the migration commit, making hard for the reviewer to review the code

Sorry for the inconvenience.

https://github.com/ForgeFlow

2024-05-07 15:42 UTC, AaronHForgeFlow commented
Tested scrap operations with the scrap completion. LGTM

(I am not reviewing myself, the migration was done in the superseded PR)

2024-05-07 15:43 UTC, AaronHForgeFlow commented
There is only one issue with the rma_scrap view, with some fields not being displayed (I think they can be removed from the view)

![image](https://github.com/ForgeFlow/stock-rma/assets/19620251/520115a3-a6eb-4cf7-9545-178ae68689b5)

2024-08-02 17:06 UTC, RLeeOSI commented
@AaronHForgeFlow Found a minor issue with creating a scrap order from the RMA order. 

If the product to be scrapped is serial tracked, the scrap form view makes the quantity field readonly. There's an onchange on the product_id field that is supposed to set the quantity to 1 if the product is serial tracked, but it is not triggered. The result is that the quantity is set to 0 and is readonly. Calling the onchange method after creating the scrap order should fix this.

2024-08-05 07:31 UTC, AaronHForgeFlow commented
@RLeeOSI thanks for the notice! I will fix that. Anyway, if you create a PR to my branch I would appreciate it.

2024-08-22 12:38 UTC, AaronHForgeFlow commented
@RLeeOSI I see that in the Scrap order the quantiy is readonly, but it seems that is standard Odoo. When the product is serial tracked then the quantity is readonly.

In the wizard, I can see I can put a different quantity even if the product is serial:

This quantity is propagated to the scrap order and can't be changed:
![2024-08-22_14-36](https://github.com/user-attachments/assets/3bc91486-a6c6-4406-9be9-20be45e80e6e)

So the solution I think is to force the quantity in the wizard to be 1. Same as Odoo does with manual scrap orders.

2024-08-22 15:14 UTC, AaronHForgeFlow commented
Rebasing just to confirm tests fail and the module needs an amendment.

2025-04-22 14:27 UTC, LoisRForgeFlow commented on rma_scrap/models/stock_scrap.py
> +    def action_validate(self):
@ThiagoMForgeFlow do your comment for v18 also apply here? https://github.com/ForgeFlow/stock-rma/pull/562#pullrequestreview-2756360066

2025-04-22 14:28 UTC, DavidJForgeFlow requested changes

2025-04-22 14:28 UTC, DavidJForgeFlow commented on rma_scrap/views/rma_order_view.xml
> +                <field name="scrap_policy" invisible="True" />
should be `column_invisible` instead

2025-04-23 09:59 UTC, AaronHForgeFlow commented on rma_scrap/views/rma_order_view.xml
> +                <field name="scrap_policy" invisible="True" />
done!

2025-04-23 10:00 UTC, AaronHForgeFlow commented on rma_scrap/models/stock_scrap.py
> +    def action_validate(self):
I removed it, it does not change anything so I think it was a mistake

2025-04-23 10:15 UTC, AaronHForgeFlow commented on rma_scrap/models/stock_scrap.py
> +    def action_validate(self):
Well, I have to look into it deeper. It seems tests fail if that code is removed.

2025-06-25 12:59 UTC, LoisRForgeFlow commented
@AaronHForgeFlow likely you need this https://github.com/ForgeFlow/stock-rma/pull/623/commits/95665c67e07cf47b8e8e5cff6584c193ac4a470c ??

2026-01-18 12:06 UTC, closed without merging