[18.0][MIG] rma_purchase
ForgeFlow/stock-rma pull request #560
Opened 2024-11-28 08:58 UTC by JasminSForgeFlow

Depends on:

- https://github.com/ForgeFlow/stock-rma/pull/558
- https://github.com/ForgeFlow/stock-rma/pull/559

2025-04-22 14:28 UTC, LoisRForgeFlow commented
Rebased

2025-04-22 14:40 UTC, LoisRForgeFlow requested changes
@JasminSForgeFlow After rebasing, tests and CI are failing, could you have a look?

2025-04-24 07:31 UTC, JasminSForgeFlow commented
> @JasminSForgeFlow After rebasing, tests and CI are failing, could you have a look?
It is fixed. The tests regarding the refund price being different from the PO price were removed, and a note was added for the same.

Because Odoo does not reconcile different amounts automatically

2025-04-29 08:08 UTC, LoisRForgeFlow commented
> > @JasminSForgeFlow After rebasing, tests and CI are failing, could you have a look?
> 
> It is fixed. The tests regarding the refund price being different from the PO price were removed, and a note was added for the same.
> 
> Because Odoo does not reconcile differece amounts automatically

@AaronHForgeFlow what do you think?

2025-06-25 08:54 UTC, LoisRForgeFlow commented
@AaronHForgeFlow a gentle reminder :)

2025-06-30 09:41 UTC, AaronHForgeFlow commented
I think it can be this commit was not forward ported to newer versions: https://github.com/ForgeFlow/stock-rma/pull/518 for some reason only the test was forward ported

2025-07-02 13:13 UTC, AaronHForgeFlow commented
@JasminSForgeFlow I confirm this feature is not working in v17 either, I will provide a fix soon. I will be adding that test back in here as well.

2025-07-03 08:59 UTC, AaronHForgeFlow commented
@LoisRForgeFlow I think now th 3 versions are aligned with:

https://github.com/ForgeFlow/stock-rma/pull/667 and
https://github.com/ForgeFlow/stock-rma/pull/666/

This is ready now.

2025-07-03 09:16 UTC, LoisRForgeFlow approved these changes
LGTM

2025-07-03 09:16 UTC, merged