[18.0][MIG] rma_sale
ForgeFlow/stock-rma pull request #561
Opened 2024-11-28 12:36 UTC by JasminSForgeFlow

Depends on:

- https://github.com/ForgeFlow/stock-rma/pull/558
- https://github.com/ForgeFlow/stock-rma/pull/559

2025-02-19 12:54 UTC, DavidJForgeFlow commented
Hi @JasminSForgeFlow could you please add changes from #578?
`c59afca9fc97067e2dc7594e61365fee41e79b09`

2025-03-21 05:38 UTC, JasminSForgeFlow commented
> c3a70ab666627483d12f37b93ce2ae5585d86c14

Done, Thanks

2025-04-10 14:12 UTC, AaronHForgeFlow commented
Hi Jasmin! I think those 2 fields can be hidden from the wizard that creates new sales quotation:
![image](https://github.com/user-attachments/assets/08253c03-96d3-4a08-bbcd-5e6025fa4436)

Also you can merge this https://github.com/ForgeFlow/stock-rma/pull/626 on this branch, I think it is ok to include it.

2025-04-11 04:54 UTC, JasminSForgeFlow commented
> Hi Jasmin! I think those 2 fields can be hidden from the wizard that creates new sales quotation: ![image](https://private-user-images.githubusercontent.com/19620251/432331524-08253c03-96d3-4a08-bbcd-5e6025fa4436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDQzNDczNzYsIm5iZiI6MTc0NDM0NzA3NiwicGF0aCI6Ii8xOTYyMDI1MS80MzIzMzE1MjQtMDgyNTNjMDMtOTZkMy00YTA4LWJiY2QtNWU2MDI1ZmE0NDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDExVDA0NTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMzM5ODE3ZDBlNmY3OTRkODE4M2ZkYjM5MmIwNTY4OGQ2M2UxMmRmYzJiODNkY2VmYTFkMjYyNmRmMzVmMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mw0tINd01WzsRTH9z1mUvnmg-KxeEd4H3UOdfACLXwk)
> 
> Also you can merge this #626 on this branch, I think it is ok to include it.

Done, Thanks

2025-04-22 14:42 UTC, LoisRForgeFlow commented
Rebased

2025-04-22 14:54 UTC, LoisRForgeFlow requested changes
@JasminSForgeFlow Add from sale order in RMA group is not working.

1. Click "Add from Sales Order" in RMA group.
2. Try to add several lots related to a SO line:
![image](https://github.com/user-attachments/assets/af35555f-bd0a-41e5-a8b8-c41f8aa3cf6e)

3. Click "Confirm".

Issue: no RMA line created.



Also, there are 2 commits from v17 not present here, could you cherry-pick them here too?

![image](https://github.com/user-attachments/assets/d479d45f-8fef-411f-b8d9-2e871edcaa22)

2025-04-23 06:51 UTC, JasminSForgeFlow commented
> @JasminSForgeFlow Add from sale order in RMA group is not working.
> 
> 1. Click "Add from Sales Order" in RMA group.
> 2. Try to add several lots related to a SO line:
>    ![image](https://private-user-images.githubusercontent.com/23449160/436132019-af35555f-bd0a-41e5-a8b8-c41f8aa3cf6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzODE5OTQsIm5iZiI6MTc0NTM4MTY5NCwicGF0aCI6Ii8yMzQ0OTE2MC80MzYxMzIwMTktYWYzNTU1NWYtYmQwYS00MWU1LWE4YjgtYzQxZjhhYTNjZjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDIzVDA0MTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NjhjODA3MWM5MmJlMmEwZTczMjU1MmY1ZGJmYzUwNTAyYWY0NDFhM2Y5YjlhMzQ4MTM4OTBhMGVlY2I4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._Oahnwlp_IsIPSK8jSaB5EnC78XfRCtRa-qa8z1kmDA)
> 3. Click "Confirm".
> 
> Issue: no RMA line created.
> 
> Also, there are 2 commits from v17 not present here, could you cherry-pick them here too?
> 
> ![image](https://private-user-images.githubusercontent.com/23449160/436133206-d479d45f-8fef-411f-b8d9-2e871edcaa22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzODE5OTQsIm5iZiI6MTc0NTM4MTY5NCwicGF0aCI6Ii8yMzQ0OTE2MC80MzYxMzMyMDYtZDQ3OWQ0NWYtOGZlZi00MTFmLWI4ZDktMmU4NzFlZGNhYTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDIzVDA0MTQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4M2I3ZDY1Y2VlZDdkNDE5NzQzYmU3YjM3NzgxYmQ5YWVjZmE3MWFiNWUzYWQ4MzFkZGUzNDQ2NjYwMDQ0NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OCDPS4vYlXtmwahDzq96dg5qB47EWrDyJyqmaTGoxuE)

https://github.com/user-attachments/assets/2d7f975e-8dd7-429c-9cc2-f543c95adbcb

@LoisRForgeFlow 
It seems working

Two commits have been added

2025-04-23 07:34 UTC, LoisRForgeFlow approved these changes
I double checked and in my case I hadn't completed the last step of the SO delivery, after finishing the delivery the wizard to add from SO worked as expected.

Thanks for fixing pre-commit and adding the 2 missing commits

LGTM

2025-04-23 07:34 UTC, merged