[18.0][MIG] rma_scrap
ForgeFlow/stock-rma pull request #562
Opened 2024-11-29 08:53 UTC by JasminSForgeFlow

Depends on:

- https://github.com/ForgeFlow/stock-rma/pull/558

2025-04-10 11:36 UTC, ThiagoMForgeFlow requested changes

2025-04-10 11:36 UTC, ThiagoMForgeFlow commented on rma_scrap/models/stock_scrap.py
> +    def action_validate(self):
Override this method was a mistake from the 16.0 migration. Could you remove it please?

2025-04-11 04:56 UTC, JasminSForgeFlow commented on rma_scrap/models/stock_scrap.py
> +    def action_validate(self):
Done, Thanks

2025-04-17 14:43 UTC, LoisRForgeFlow commented
Rebased

2025-06-25 08:53 UTC, LoisRForgeFlow commented
@ThiagoMForgeFlow could you review again?

2025-06-25 11:54 UTC, ThiagoMForgeFlow approved these changes

2025-06-25 12:58 UTC, LoisRForgeFlow approved these changes
LGTM

2025-06-25 12:58 UTC, merged