[WIP][MIG][12.0] rma_purchase
ForgeFlow/stock-rma pull request #69
Opened 2019-03-20 12:56 UTC by murtuzasaleh

WIP

2019-03-26 10:53 UTC, murtuzasaleh commented
@lreficent What is the use of this method [def new](https://github.com/Eficent/stock-rma/blame/d9c514009e4439c731846a2bcc934d313d3f944a/rma_purchase/models/purchase_order.py#L11) in rma_purchase module, It is WIP in v11 or other Use of it?
Because it is not called in rma_purchase module.

2019-03-27 08:34 UTC, aheficent commented
> @lreficent What is the use of this method [def new](https://github.com/Eficent/stock-rma/blame/d9c514009e4439c731846a2bcc934d313d3f944a/rma_purchase/models/purchase_order.py#L11) in rma_purchase module, It is WIP in v11 or other Use of it?
> Because it is not called in rma_purchase module.

The method new is called when creating a new purchase order. It is like the create method, it is called when creating a new record. That is why is calling super at the beginning.

2019-03-27 13:24 UTC, murtuzasaleh commented
@aheficent Can you please review this PR.

2019-04-03 17:56 UTC, max3903 commented
@osi-scampbell Please review, test and comment. Thanks.

2019-04-11 12:23 UTC, murtuzasaleh commented
@osi-scampbell Can you please review this PR.

2019-04-12 18:39 UTC, osi-scampbell commented
Code installs clean, smart buttons and fields are added onto an RMA form. No bugs or errors found. Approved

2019-04-12 18:49 UTC, max3903 commented
@aheficent What are we missing to get this merged?

2019-05-16 11:57 UTC, bjeficent requested changes
I have tested it locally and it works properly. I'll add a change: If a product is selected, add the product to the domain.

2019-05-16 11:57 UTC, bjeficent commented on rma_purchase/models/rma_order_line.py
> +
```suggestion
    @api.onchange('product_id', 'partner_id')
    def _onchange_product_id(self):
        """Domain for purchase_order_line_id is computed here to make it dynamic."""
        res = super(RmaOrderLine, self)._onchange_product_id()
        if not res.get('domain'):
            res['domain'] = {}
        domain = [
            '|',
            ('order_id.partner_id', '=', self.partner_id.id),
            ('order_id.partner_id', 'child_of', self.partner_id.id)]
        if self.product_id:
            domain.append(('product_id', '=', self.product_id.id))
        res['domain']['purchase_order_line_id'] = domain
        return res
```

2019-05-17 10:27 UTC, bjeficent approved these changes
LGTM :+1:

2019-05-17 10:51 UTC, murtuzasaleh commented
@aheficent Can you please review this PR.

2019-05-17 15:22 UTC, AaronHForgeFlow approved these changes
:+1: works fine. Thanks

2019-05-17 15:23 UTC, merged

2019-05-17 20:36 UTC, max3903 commented
Yay! Thank you!